### PR TITLE
fix: cypress now runs on pull_request

### LINKED ISSUE #58: Fix Cypress Tests
> The last successful run of Cypress was [three months ago](https://github.com/ubiquity/work.ubq.fi/actions/runs/8199248704) with a single test, so it appears as though they were never stable in the first place @gentlementlegen 

> Perhaps the Cypress tests should all be fixed as part of a separate task.

_Originally posted by @0x4007 in https://github.com/ubiquity/work.ubq.fi/issues/57#issuecomment-2147352850_

### PR DESCRIPTION
**Pull request by gentlementlegen**
Resolves #58

### CODE REVIEW

**Comment by gentlementlegen** [comment]
## What is this?

Unlike when we are using Jest, Cypress cannot stub Supabase for auth, because we use a bundler that will create its own code, which is not accessible through Cypress itself. As such, it is not possible to fake login, or auth sessions.

Every tutorial I found suggests to have a separate Supabase session instantiated within Cypress, and store the credentials within the browser. This introduces 2 problems:
- we would have to enable credentials login, since we only have OAuth
- we would have to store valid credentials, which we can't since we do not have access to secrets

The workaround I implemented for this is to read the `NODE_ENV` value and if set to `test` then we would just read the `token` from the local storage, because we are able to manipulate this through Cypress thus fake login.

For the rest just fixed the tests, added missing interceptions, and fixed toast conditions. Might collide with https://github.com/ubiquity/work.ubq.fi/pull/57
Successful run: https://github.com/ubiquity/work.ubq.fi/actions/runs/9371378749

**Comment by 0x4007** [comment]
> Might collide with https://github.com/ubiquity/work.ubq.fi/pull/57
> 
> Successful run: https://github.com/ubiquity/work.ubq.fi/actions/runs/9371378749

Given that #57 was opened first and is the reason this task was created, it makes sense for you to accept it first and then accommodate necessary changes here

**Review by rndquu — APPROVED** [review]

**Comment by 0x4007** [comment]
> > Might collide with #57
> > Successful run: https://github.com/ubiquity/work.ubq.fi/actions/runs/9371378749
> 
> Given that #57 was opened first and is the reason this task was created, it makes sense for you to accept it first and then accommodate necessary changes here

Might be appropriate to properly configure a merge queue. Although I couldn't figure it out last time i tried @gentlementlegen

**Review by whilefoo — APPROVED** [review]
I'm not too familiar with this codebase but it looks good to me

File: src/home/fetch-github/fetch-issues-preview.ts [hunk 1]
```diff
@@ -65,16 +64,10 @@ export async function fetchIssuePreviews(): Promise<TaskNoFull[]> {
...
+      await handleRateLimit(octokit, error as RequestError);
     } else {
-      // renderErrorInModal(error as Error, "You have been rate limited. Please login to increase your limits."); // @DEV: user another method to render the modal not as an error
-      displayPopupMessage({
-        modalHeader: "GitHub API rate limit exceeded.",
-        modalBody: "You have been rate limited. Please login to increase your limits.",
-        isError: false,
-      });
-      gitHubLoginButton?.classList.add("highlight");
+      throw error;
```
Comment (gentlementlegen) [inline src/home/fetch-github/fetch-issues-preview.ts:70]: @0x4007 Had to change this to bubble up the error, because previous code logic would display the error rate limit whatever the error was, which is wrong on a 500 network error for example.

File: cypress.config.ts [hunk 2]
```diff
@@ -11,21 +11,6 @@ export default defineConfig({
   },
   viewportHeight: 900,
   viewportWidth: 1440,
-  env: readEnvironmentVariables(),
```
Comment (0x4007) [inline cypress.config.ts:14]: This is useful you should consider leaving it in

File: cypress/e2e/devpool.cy.ts [hunk 3]
```diff
@@ -175,36 +185,45 @@ describe("DevPool", () => {
...
+          user: githubUser,
+        })
+      );
+    }).as("githubPage");
     cy.visit("/");
     // Check that there is no text field visible for sorting
     cy.get("#filter").should("not.be.visible");
     cy.get("#github-login-button").click();
-    cy.origin("https://github.com/login", () => {
-      const username = Cypress.env("UBIQUIBOT_GITHUB_USERNAME");
```
Comment (0x4007) [inline cypress/e2e/devpool.cy.ts:189]: Are these environment variables not needed anymore?

File: src/home/fetch-github/fetch-issues-preview.ts (hunk 1 above)
Comment (0x4007) [reply src/home/fetch-github/fetch-issues-preview.ts:70]: Well then you should catch and display the specified error for rate limiting (I think it's a 403?) 

Otherwise the raw errors don't look as presentable.

File: static/style/inverted-style.css [hunk 4]
```diff
@@ -688,4 +688,9 @@
     align-items: center;
     margin-right: 8px;
   }
+  .github-avatar-default {
+    width: 48px;
+    height: 48px;
+    background-color: #7f7f7f;
```
Comment (0x4007) [inline static/style/inverted-style.css]:
```suggestion
    background-color: #808080;
```

File: cypress/e2e/devpool.cy.ts (hunk 3 above)
Comment (gentlementlegen) [reply cypress/e2e/devpool.cy.ts:189]: No, the login is now faked to avoid tests crashing due to missing environment variables.

File: cypress.config.ts (hunk 2 above)
Comment (gentlementlegen) [reply cypress.config.ts:14]: I can leave it but it will be a function returning empty content, is that fine?

File: src/home/fetch-github/fetch-issues-preview.ts (hunk 1 above)
Comment (gentlementlegen) [reply src/home/fetch-github/fetch-issues-preview.ts:70]: The full logic within the `catch` clause is:
```TypeScript
    if (!!error && typeof error === "object" && "status" in error && error.status === 403) {
      await handleRateLimit(octokit, error as RequestError);
    } else {
      throw error;
    }
```

So I think we are fine. I tried and get a nice error on `403` and a generic one for the rest.

File: cypress.config.ts (hunk 2 above)
Comment (0x4007) [reply cypress.config.ts:14]: I suppose we should remove useless logic!

Comment (gentlementlegen) [reply cypress.config.ts:14]: Well these are not needed for now since it's mocked. We can always find the logic back within the Git history if needed, so will remove it for now.

**Review by 0x4007 — APPROVED** [review]
