### PR TITLE
fix: fixed e2e test

### LINKED ISSUE #109: ci: fix cypress e2e tests
Check [this](https://github.com/ubiquity/work.ubq.fi/actions/runs/11216977982/job/31177473349) failing cypress e2e testing workflow.

As far as I understand it fails because now `work.ubq.fi` [fetches](https://github.com/ubiquity/work.ubq.fi/blob/23d04fb764b63e8445453e2e9ff44b84afbce624/src/home/fetch-github/fetch-issues-full.ts#L5) github issues from the [devpool-issues.json](https://github.com/ubiquity/devpool-directory/blob/79330a6d55e22543a3bb102817e5075cb4dc4d5b/devpool-issues.json) while e2e tests [mock](https://github.com/ubiquity/work.ubq.fi/blob/23d04fb764b63e8445453e2e9ff44b84afbce624/cypress/e2e/devpool.cy.ts#L18-L23) regular github API calls.

What should be done:
- refactor [e2e tests](https://github.com/ubiquity/work.ubq.fi/blob/23d04fb764b63e8445453e2e9ff44b84afbce624/cypress/e2e/devpool.cy.ts) according to the current logic

### PR DESCRIPTION
**Pull request by ariesgun**
Resolves #109

### CODE REVIEW

File: src/home/rendering/display-github-user-information.ts
Comment (ariesgun) [inline src/home/rendering/display-github-user-information.ts:1]: Updated so that this test `Should display filters on small devices` can pass

**Comment by EresDev** [comment]
Are these tests passing on your local computer? 

For me, some tests are failing locally.  

image

**Comment by ariesgun** [comment]
> Did you run these tests on your local computer? if yes, are they passing there?
> 
> For me, some tests are failing locally.
> 
> image

Yes. What are the errors?

**Comment by EresDev** [comment]
> Yes. What are the errors?

timeout error. But I have increased the timeout to half a minute for each test, and they still fail with timeout.

**Comment by EresDev** [comment]
https://github.com/user-attachments/assets/3675579f-c171-47f9-87f8-d9c5a163a4f3

**Comment by ariesgun** [comment]
> qa.mp4

It could be your .env.
Did you set NODE_ENV=test?

File: cypress/e2e/devpool.cy.ts [hunk 1]
```diff
@@ -4,103 +4,41 @@ import { Session } from "@supabase/supabase-js";
 describe("DevPool", () => {
   let issue1: RestEndpointMethodTypes["issues"]["get"]["response"]["data"];
   let issue2: RestEndpointMethodTypes["issues"]["get"]["response"]["data"];
+  let issue3: RestEndpointMethodTypes["issues"]["get"]["response"]["data"];
+  let avatars: RestEndpointMethodTypes["issues"]["get"]["response"]["data"];
```
Comment (EresDev) [inline cypress/e2e/devpool.cy.ts]: Looks like incorrect type for avatars.

**Review by EresDev — CHANGES_REQUESTED** [review]
> > qa.mp4
> 
> It could be your .env. Did you set NODE_ENV=test?

It worked. Thanks.

Working well overall.

File: cypress/e2e/devpool.cy.ts (hunk 1 above)
Comment (ariesgun) [reply cypress/e2e/devpool.cy.ts]: Indeed. Fixed

**Review by EresDev — APPROVED** [review]

File: cypress/fixtures/avatars.json [hunk 2]
```diff
@@ -0,0 +1,22 @@
+[
+    {
+        "ownerName": "ubiquitybot[bot]",
```
Comment (0x4007) [inline cypress/fixtures/avatars.json]: This owner I don't recognize and looks wrong

File: cypress/fixtures/issue-2.json [hunk 3]
```diff
@@ -33,8 +33,8 @@
     {
       "id": 5390000409,
       "node_id": "LA_kwDOJWyCVM8AAAABQUThGQ",
-      "url": "https://api.github.com/repos/ubiquity/devpool-directory/labels/Pricing:%20100%20USD",
-      "name": "Pricing: 100 USD",
```
Comment (0x4007) [inline cypress/fixtures/issue-2.json:37]: We have this changed in the directory backend to not clash with special bot functions. Are you sure this is correct?

File: cypress/fixtures/avatars.json (hunk 2 above)
Comment (ariesgun) [reply cypress/fixtures/avatars.json]: It is a test file. Does it matter?

File: cypress/fixtures/issue-2.json (hunk 3 above)
Comment (ariesgun) [reply cypress/fixtures/issue-2.json:37]: Updated the test files with the versions that match the real output

File: cypress/fixtures/avatars.json (hunk 2 above)
Comment (ariesgun) [reply cypress/fixtures/avatars.json]: Updated the test file with the versions that match the real output

**Review by 0x4007 — APPROVED** [review]
